#cloud-config
users:
    - name: ubuntu
      sudo: ALL=(ALL) NOPASSWD:ALL
      groups: users, admin
      home: /home/ubuntu
      shell: /bin/bash
      ssh_authorized_keys:
          - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQD1Ja9kgnwTKWNHfZJc0YClBVJ5hISO5LJs1DXFXAaIqrVxN5eWwOITz5+GPHr3N60vjAp1DoLzHWK4C+Ajk2eoJF7VAD1HQHgIG1gs/k4t+IhHb2sqo0Lt2eSPN8noJciNgSiXSaVJ23swNRKO/pvjJUg7bjv+Pe6xbeaCmt2lI2OREF6wI16e/NGB17OirTie7UiJUCMEhaGIBkZI2c4xWUdpGHg3zV3xGrqoVXTyBPtQtBYG7KsTox9camt0bnEPfVfI+RbG3JAfKTxSVQraTWJGm1r4poD8jVpxmV5s82ld8VRLXhnaNZoH+33QeVdBm2BFn7TwtJ9x7KL7/ZQ9 aws-key
ssh_pwauth: false
disable_root: false
package_update: true
packages:
    - curl
    - wget
    - adminer
runcmd:
    - sudo apt update
    - sudo apt install apache2
    - sudo apt install php
    - sudo apt install libapache2-mod-php
    - sudo apt install php-mysqli
    - sudo systemctl restart apache2
    - sudo a2enconf adminer
