#cloud-config
users:
    - name: ubuntu
      sudo: ALL=(ALL) NOPASSWD:ALL
      groups: users, admin
      home: /home/ubuntu
      shell: /bin/bash
      ssh_authorized_keys:
          - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDIx3fNrTxxDvt9xa2Yz+o0E8xA+MG9JNuzueTFkjK8cDPcDMcFDCJJKYPdM5V0/AYrxTXyHIyYHac88FzdK3wzpT8Whm46UV9BMPG6zU49Fq0xVEVTuiPjI/6KEQTq3jL2mQjGvLmAopnz5njuCkqD969VTbJiB1tH0zEx9xQFgPT9/flt9HVBFJLo5sy+7PmtZvn9XanewtrSyKQ+F5E9FejJ4lF/alHjYySgcJuBk6t/u7ASKz+xRCkGkgqt6d3FaHuM4EqmDkwt5gn1EgKlkpbT1YnymIliOQb9fS2YZTkE6i36fmscirm9xo+o22qfwVqqAYwnZy11xrSnaI2J aws-key
ssh_pwauth: false
disable_root: false
package_update: true
packages:
    - mariadb-server
runcmd:
    - sudo mysql -sfu root -e "GRANT ALL ON *.* TO 'admin'@'%' IDENTIFIED BY 'password' WITH GRANT OPTION;"
    - sudo sed -i 's/127.0.0.1/0.0.0.0/g' /etc/mysql/mariadb.conf.d/50-server.cnf
    - sudo systemctl restart mariadb.service
